# Site
repository: "Git repository where your resume will be hosted"
favicon: ""

# Content configuration version
version: 2

# Personal info
name: "First Name Last Name"
title: "Academic Portfolio"

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: "amaobiotiji"
github_username: "amaoti"
professional_portfolio: "https://amaoti.github.io/portfolio/"

# Google Analytics and Tag Manager
gtm: "GTM-0000000"
gtag: "UA-00000000-0"
google_analytics: "UA-00000000-0"

# About Section
about_profile_image: "images/otiji_headshot.jpg"
about_content: |
  I completed my Master of Information at Rutgers in December 2025. My concentration was <i>Technology, Information and Management</i>. My academic work centers on digital curation, preservation strategy, metadata, and the systems that support long-term access to cultural heritage materials.

content:
  - title: "<mark><b>Master of Information Coursework</b></mark>"
    layout: list
    content:
      - layout: top-right
        title: "Rutgers University â€“ New Brunswick"
        sub_title: "Master of Information"
        caption: "GPA 4.0 | ALA Accredited | Technology, Information and Management"
        description: |
          This program brought together digital preservation, metadata standards, database design, records management, government information, knowledge organization, competitive intelligence, and the social and ethical frameworks that shape information work.

          Completed Courses:
          - <mark>MI570 Management Principles in Information Organizations</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI550 Introduction to Information Technologies</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI501 Introduction to Library and Information Professions</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI520 Organizing Information</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI535 Competitive Intelligence</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI599 Digital Preservation (Special Topic)</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI574 Knowledge Management in Organizations</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI580 Knowledge and Society</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI557 Database Design and Management</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI534 Records Management</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI524 Metadata for the Information Professional</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI502 Colloquium in Library and Information Sciences</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI566 Digital Curation</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI541 Government Information Resources</mark>
            - [course]
            - [my work]
            - [final]
          - <mark>MI503 ePortfolio Capstone</mark>
            - [course]
            - [my work]
            - [final]


  - title: "<mark><b>Student Projects & Awards</b></mark>"
    layout: list
    content:
      - layout: left
        border: weak
        title: "Unforgotten: Mount Zion and Female Union Band Society Cemeteries"
        link: "https://www.unforgotten-mtzfubs.com/"
        link_text: "Visit Project"
        additional_links:
          - title: "GitHub Repository"
            icon: "fab fa-github"
            url: "https://github.com/amaoti/black-legacy-lam"
        quote: >
          A digital exhibit and curated web archive exploring the history, preservation, and community significance of the Mount Zion and Female Union Band Society Cemeteries.
        description: |
          [Enter Text Here]

# Footer
footer_show_references: true

# Build settings
remote_theme: "sproogen/modern-resume-theme"

sass:
  sass_dir: "_sass"
  style: "compressed"

plugins:
  - "jekyll-seo-tag"

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"
